#include <ymir/hw/mpeg/mpeg_decoder.hpp>
#include <ymir/hw/mpeg/mpeg_card.hpp>

#include <catch2/catch_test_macros.hpp>

#include "mpeg_test_fixtures.hpp"

#include <span>

using namespace ymir;
using namespace ymir::test::mpeg_fixtures;

namespace {

// This fixture is a 16x16 MPEG-1 PS with MP2 audio, generated by ffmpeg.
// It is intentionally small to keep test compile times reasonable.

} // namespace

TEST_CASE("MPEGCard decodes both video and audio frames from stream with audio", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.StartPlayback();

    // Feed the video-only fixture first to verify video still works
    card.AppendStreamData(kTinyMpegProgramStream);
    card.SignalEndOfStream();

    REQUIRE(card.HasHeaders());
    CHECK(card.GetWidth() == 16);
    CHECK(card.GetHeight() == 16);

    // Video-only fixture has no audio
    CHECK_FALSE(card.HasAudio());

    REQUIRE(card.DecodeNextFrame());
    REQUIRE(card.HasCurrentFrame());

    // Audio decode should fail gracefully on video-only stream
    CHECK_FALSE(card.DecodeNextAudioFrame());
    CHECK_FALSE(card.HasCurrentAudio());
}

TEST_CASE("MPEGCard decodes audio regardless of card status (Stopped for game compat)", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.AppendStreamData(kTinyMpegProgramStream);
    card.SignalEndOfStream();

    // Card status is Ended after SignalEndOfStream; audio decode happens
    // regardless of status for game compatibility (card stays Stopped/Ended
    // to bypass MPEG polling loops, but audio still decodes for mixing).
    // Video-only fixture has no audio, so decode should fail gracefully.
    CHECK_FALSE(card.DecodeNextAudioFrame());
    CHECK_FALSE(card.HasCurrentAudio());

    CHECK(card.GetStatus() == mpeg::MPEGCardStatus::Ended);
}

TEST_CASE("MPEGCard audio frame has correct sample count", "[mpeg][movie-card][audio]") {
    // The DecodedAudioFrame type defines the expected sample count
    CHECK(mpeg::DecodedAudioFrame::kSamplesPerFrame == 1152);
    CHECK(mpeg::DecodedAudioFrame{}.samples.size() == 1152 * 2);
}

TEST_CASE("MPEGCard GetNextAudioSample returns samples regardless of card status", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.AppendStreamData(kTinyMpegProgramStreamWithAudio);
    card.SignalEndOfStream();

    // Audio decode happens regardless of card status (Stopped/Ended) for
    // game compatibility. The fixture has audio, so samples should be returned.
    sint16 left, right;
    CHECK(card.GetNextAudioSample(left, right));
}

TEST_CASE("MPEGCard GetNextAudioSample returns false on video-only stream", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.StartPlayback();
    card.AppendStreamData(kTinyMpegProgramStream);
    card.SignalEndOfStream();

    REQUIRE(card.HasHeaders());
    CHECK_FALSE(card.HasAudio());

    sint16 left, right;
    CHECK_FALSE(card.GetNextAudioSample(left, right));
}

TEST_CASE("MPEGCard GetNextAudioSample decodes and returns samples from audio stream",
          "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.StartPlayback();
    card.AppendStreamData(kTinyMpegProgramStreamWithAudio);
    card.SignalEndOfStream();

    REQUIRE(card.HasHeaders());
    REQUIRE(card.HasAudio());
    CHECK(card.GetAudioSampleRate() == 44100);

    // GetNextAudioSample should auto-decode the first audio frame and return samples
    sint16 left, right;
    REQUIRE(card.GetNextAudioSample(left, right));

    // Verify subsequent samples come from the same frame (sequential read of 1152 samples)
    uint32 count = 1;
    while (count < mpeg::DecodedAudioFrame::kSamplesPerFrame) {
        REQUIRE(card.GetNextAudioSample(left, right));
        ++count;
    }

    // After consuming all 1152 samples, the next call should auto-decode the next frame
    // (or return false if the stream has ended)
    // The tiny fixture has very few audio frames, so it may end here
    card.GetNextAudioSample(left, right); // may succeed or fail depending on stream length
}
