#include <ymir/hw/mpeg/mpeg_decoder.hpp>
#include <ymir/hw/mpeg/mpeg_card.hpp>

#include <catch2/catch_test_macros.hpp>

#include "mpeg_test_fixtures.hpp"

#include <span>

using namespace ymir;
using namespace ymir::test::mpeg_fixtures;

namespace {

// This fixture is a 16x16 MPEG-1 PS with MP2 audio, generated by ffmpeg.
// It is intentionally small to keep test compile times reasonable.

} // namespace

TEST_CASE("MPEGCard decodes both video and audio frames from stream with audio", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.StartPlayback();

    // Feed the video-only fixture first to verify video still works
    card.AppendStreamData(kTinyMpegProgramStream);
    card.SignalEndOfStream();

    REQUIRE(card.HasHeaders());
    CHECK(card.GetWidth() == 16);
    CHECK(card.GetHeight() == 16);

    // Video-only fixture has no audio
    CHECK_FALSE(card.HasAudio());

    REQUIRE(card.DecodeNextFrame());
    REQUIRE(card.HasCurrentFrame());

    // Audio decode should fail gracefully on video-only stream
    CHECK_FALSE(card.DecodeNextAudioFrame());
    CHECK_FALSE(card.HasCurrentAudio());
}

TEST_CASE("MPEGCard does not decode audio while stopped", "[mpeg][movie-card][audio]") {
    mpeg::MPEGCard card;

    card.Initialize();
    card.AppendStreamData(kTinyMpegProgramStream);
    card.SignalEndOfStream();

    // Not started -> should not decode
    CHECK_FALSE(card.DecodeNextAudioFrame());
    CHECK_FALSE(card.HasCurrentAudio());

    CHECK(card.GetStatus() == mpeg::MPEGCardStatus::Stopped);
}

TEST_CASE("MPEGCard audio frame has correct sample count", "[mpeg][movie-card][audio]") {
    // The DecodedAudioFrame type defines the expected sample count
    CHECK(mpeg::DecodedAudioFrame::kSamplesPerFrame == 1152);
    CHECK(mpeg::DecodedAudioFrame{}.samples.size() == 1152 * 2);
}
